"""
Main agentic pipeline orchestrator.
"""

import json
import shutil
from pathlib import Path

from .agent import AgenticImageProcessor
from .colmap_processor import COLMAPProcessor
from .config import PipelineConfig
from .models.base import ModelRegistry
from .models.super_resolution import DiffBIRModel
from .models.view_generator import StableVirtualCameraModel
from .utils import analyze_image_quality, detect_image_issues


class AgenticPipeline:
    """Main agentic pipeline for processing images into 3DGS datasets."""

    def __init__(self, config: PipelineConfig):
        self.config: PipelineConfig = config
        self.model_registry: ModelRegistry = ModelRegistry()
        self.colmap_processor: COLMAPProcessor = COLMAPProcessor(
            quality=config.model.colmap_quality, device=config.model.device
        )

        # Initialize models
        self._initialize_models()

        # Initialize agent
        self.agent: AgenticImageProcessor = AgenticImageProcessor(
            config.llm, self.model_registry
        )

    def _initialize_models(self):
        """Initialize and register all available models."""
        # Register Stable Virtual Camera model
        view_generator = StableVirtualCameraModel(
            device=self.config.model.device, model_version=1.1
        )
        self.model_registry.register("view_generation", view_generator)

        # Register DiffBIR model
        super_resolution = DiffBIRModel(
            device=self.config.model.device,
            scale=self.config.model.super_resolution_factor,
        )
        self.model_registry.register("super_resolution", super_resolution)

    def process(
        self,
        input_image: Path,
        output_dir: Path,
        num_views: int | None = None,
        skip_colmap: bool = False,
    ) -> dict[str, object]:
        """
        Process a single input image into a 3DGS dataset.

        Args:
            input_image: Path to the input image
            output_dir: Directory for output dataset
            num_views: Number of views to generate (if None, agent decides)
            skip_colmap: Skip COLMAP preprocessing

        Returns:
            Dictionary with processing results
        """
        input_image = Path(input_image)
        output_dir = Path(output_dir)

        if not input_image.exists():
            return {"success": False, "error": f"Input image not found: {input_image}"}

        # Create output directory structure
        output_dir.mkdir(parents=True, exist_ok=True)
        temp_dir = output_dir / "temp"
        temp_dir.mkdir(exist_ok=True)

        # Step 1: Analyze input image
        if self.config.verbose:
            print("Analyzing input image...")

        analysis = analyze_image_quality(input_image)
        issues = detect_image_issues(input_image)

        if self.config.verbose:
            print(f"Image analysis: {analysis}")
            if issues:
                print(f"Detected issues: {issues}")

        # Step 2: Plan processing with agent
        if self.config.verbose:
            print("Planning processing pipeline...")

        plan_result = self.agent.plan_processing(input_image, temp_dir)
        if not plan_result["success"]:
            return {
                "success": False,
                "error": f"Planning failed: {plan_result['plan']}",
            }

        if self.config.verbose:
            print(f"Processing plan: {plan_result['plan']}")

        # Step 3: Execute processing
        if self.config.verbose:
            print("Executing processing pipeline...")

        execution_result = self.agent.execute_plan(plan_result["plan"])
        if not execution_result["success"]:
            return {
                "success": False,
                "error": f"Execution failed: {execution_result['result']}",
            }

        # Step 4: Collect generated images
        generated_images = self._collect_generated_images(temp_dir)

        if not generated_images:
            return {
                "success": False,
                "error": "No images were generated by the processing pipeline",
            }

        # Step 5: Run COLMAP preprocessing (if not skipped)
        if not skip_colmap and not self.config.skip_colmap:
            if self.config.verbose:
                print("Running COLMAP preprocessing...")

            colmap_result = self.colmap_processor.process_images(
                image_dir=temp_dir, output_dir=output_dir / "colmap_temp"
            )

            if not colmap_result["success"]:
                if self.config.verbose:
                    print(
                        f"COLMAP failed: {colmap_result.get('error', 'Unknown error')}"
                    )
                    print("Continuing without COLMAP preprocessing...")
            else:
                # Create final dataset structure
                self._create_final_dataset(
                    images_dir=temp_dir,
                    colmap_dir=colmap_result["sparse_dir"],
                    output_dir=output_dir,
                )
        else:
            # Just copy images to final structure
            self._create_final_dataset(
                images_dir=temp_dir, colmap_dir=None, output_dir=output_dir
            )

        # Clean up temp directory
        shutil.rmtree(temp_dir, ignore_errors=True)

        return {
            "success": True,
            "output_dir": output_dir,
            "generated_images": len(generated_images),
            "analysis": analysis,
            "issues": issues,
            "plan": plan_result["plan"],
            "execution_result": execution_result["result"],
        }

    def _collect_generated_images(self, temp_dir: Path) -> list[Path]:
        """Collect all generated images from the temp directory."""
        image_extensions = {".jpg", ".jpeg", ".png", ".bmp", ".tiff"}
        generated_images = []

        for file_path in temp_dir.rglob("*"):
            if file_path.is_file() and file_path.suffix.lower() in image_extensions:
                generated_images.append(file_path)

        return generated_images

    def _create_final_dataset(
        self, images_dir: Path, colmap_dir: Path | None, output_dir: Path
    ):
        """Create the final dataset structure."""
        # Create images directory
        final_images_dir = output_dir / "images"
        final_images_dir.mkdir(exist_ok=True)

        # Copy all images
        for img_file in images_dir.glob("*"):
            if img_file.suffix.lower() in {".jpg", ".jpeg", ".png", ".bmp", ".tiff"}:
                shutil.copy2(img_file, final_images_dir / img_file.name)

        # Copy COLMAP results if available
        if colmap_dir and colmap_dir.exists():
            final_sparse_dir = output_dir / "sparse" / "0"
            final_sparse_dir.mkdir(parents=True, exist_ok=True)

            for file in colmap_dir.glob("*.bin"):
                shutil.copy2(file, final_sparse_dir / file.name)

        # Create metadata file
        metadata = {
            "dataset_type": "3dgs_ready",
            "num_images": len(list(final_images_dir.glob("*"))),
            "has_colmap": colmap_dir is not None and colmap_dir.exists(),
            "created_by": "agentic_image2dataset",
        }

        with open(output_dir / "metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)

    def get_available_models(self) -> list[str]:
        """Get list of available models."""
        return self.model_registry.list_available()

    def get_model_info(self, model_name: str) -> dict[str, object] | None:
        """Get information about a specific model."""
        model = self.model_registry.get(model_name)
        if model is None:
            return None

        return {
            "name": model_name,
            "description": model.get_description(),
        }
